- name: Install Wordpress (from EPEL)
  yum: pkg=wordpress state=present
  tags: wordpress

# -  name: Install Apache config file for Wordpress
   # copy: 
    # src=etc_httpd_conf.d_wordpress.conf
    # dest=/etc/httpd/conf.d/wordpress.conf
    # owner=root
    # group=root
    # setype=httpd_config_t
    # mode=0644
   # notify: Restart webserver
   # tags: wordpress

# -  name: Install wp-config.php
   # template:
      # src=wp-config.php.j2
      # dest=/etc/wordpress/wp-config.php
      # owner=root
      # group=apache
      # setype=etc_t
      # mode=0640
   # notify: Restart webserver
   # tags: wordpress    