<br /><br />
<div id="view-content">
	<p>View script for controller <b>Guestbook</b> and script/action name <b>index</b></p>


    <p><a href="<?php echo $this->url(
            array(
                'controller' => 'Guestbook',
                'action'     => 'sign'
            ),
            'default',
            true) ?>">Sign Our Guestbook</a></p>

    Guestbook Entries: <br />
    <dl>
        <?php
        foreach ($this->entries as $entry):
?>
                <dt><a href="<?php echo $this->url(
                                       array('controller' =>'guestbook',
                                             'action'     =>'find',
                                             'id'         =>$entry->email,


                                       ),
                        'default',true

                        );?>">  <?php echo $this->escape($entry->email) ?></a></dt>
                <dd><?php echo $this->escape($entry->comment) ?></dd>
        <?php endforeach ?>
    </dl>


</div>

